### PR TITLE
Issue #62

### LINKED ISSUE #62: Missing wind speed and wind direction by pulling DWD historical data
**Describe the bug**
By pulling the DWD historical data, there is no data for wind speed and wind direction.

**To Reproduce**
1. Go to 'examples/e1_pull_DWD_historical_to_all_output_formats.py'
2. Set the DWD-pull project as:
```
DWD_pull_project = ProjectClassDWDHistorical(
        start=dt.datetime(2023, 1, 1),  # Pull the data of January 2023
        end=dt.datetime(2023, 2, 1),
        station=15000,  # Set the weather station as 15000: Aachen-Orsbach
        # specify whether nan-values should be filled when exporting
        fillna=True,
        # define results path if desired
        abs_result_folder_path=None,
    )
```
3. Check the values of wind speed and wind direction in the pulled data

**Expected behavior**
Pulled data include wind speed and direction

**Screenshots**
```
#1:for TMY3reader
double tab1(745,30)
#LOCATION,Aachen-Orsbach,,,,,50.798,6.024,0,something
#Explanation of Location line:
#   Element 7: latitude
#   Element 8: longitude
#   Element 9: time zone in hours from UTC
#
#DATA PERIODS, data available from 2023-01-01 00:00:00 (second=0) to 2023-02-01 00:00:00 (second=2678400)
# info: TMY3Reader requirement: Time 0 = 01.01. 00:00:00 at local time (see time zone above)
#
#USED DATA-COLLECTOR: ebc-weather-tool with input source DWD Historical (collected at 2024-07-05 11:33:27.679670) "-0" marks not available data
#Info: The AixLib/IBPSA TMY3reader requires the below mentioned units and measurement times. Last Check: 28.02.2022
#C1 Time in seconds. Beginning of a year is 0s.
...
#C16 Wind direction at indicated time. N=0, E=90, S=180, W=270
#C17 Wind speed in m/s at indicated time
#C18 Total sky cover in tenth at indicated time
...
#C30 Liquid precipitation quantity, TMY3Reader: not used
0	14.62	4.76	51.62	98364.17	-0	-0	347.88	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	6.25	6.25	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
3600	14.23	4.17	50.81	98398.33	-0	-0	345.08	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	10.00	10.00	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
7200	14.07	4.38	52.04	98424.17	-0	-0	356.32	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	10.00	10.00	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
10800	13.88	4.93	54.81	98453.33	-0	-0	355.89	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	10.00	10.00	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
14400	13.56	5.49	58.20	98483.33	-0	-0	355.29	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	10.00	10.00	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
18000	13.29	6.14	61.97	98525.83	-0	-0	348.69	0.00	0.00	0.00	-0	-0	-0	-0	-0	-0	8.75	8.75	-0	20000.00	-0	-0	-0	-0	-0	-0	-0	-0	-0
```

**Bug Fix Suggestion**
There are two data sources of wind speed in the CDC:

- https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/wind/
- https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/

Both sources include the wind data of January 2023, e.g.:

- From https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/wind/historical/10minutenwerte_wind_15000_20200101_20231231_hist.zip
```
STATIONS_ID;MESS_DATUM;  QN;FF_10;DD_10;eor
...
      15000;202301010000;    3;  12.3; 220;eor
      15000;202301010010;    3;  11.0; 220;eor
      15000;202301010020;    3;  10.1; 220;eor
      15000;202301010030;    3;  10.0; 220;eor
      15000;202301010040;    3;  10.6; 220;eor
      15000;202301010050;    3;  10.8; 220;eor
      15000;202301010100;    3;  12.3; 220;eor
```

- From https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/historical/stundenwerte_FF_15000_20110401_20231231_hist.zip
```
STATIONS_ID;MESS_DATUM;QN_3;   F;   D;eor
...
      15000;2023010100;   10;  12.0; 220;eor
      15000;2023010101;   10;  10.8; 220;eor
      15000;2023010102;   10;  12.2; 220;eor
      15000;2023010103;   10;  12.0; 220;eor
      15000;2023010104;   10;  11.2; 220;eor
      15000;2023010105;   10;  11.2; 220;eor
      15000;2023010106;   10;  10.7; 220;eor
```

For the wind data, now the code will try to pull the data from hourly data bank. I changed the source to 10-minute data bank and the wind data appeared.

However, the the tool should also work with hourly databank, because the data also exist there. I guess there is a bug by pulling the data or by processing the data pulled.

### PR DESCRIPTION
**Pull request by Jun-Jiang-92**
Closes #62
Changed the data source for wind speed and wind direction from hourly-databank to 10-min-datebank
Signed-off-by: Jun Jiang <jun.jiang@eonerc.rwth-aachen.de>

### CODE REVIEW

**Comment by MartinRaetz** [comment]
Thank you @Jun-Jiang-92. 
Though, we need to verify that the current behavior ist correct.

- [ ] Please review the time shifting required. See my comment in the Issue. I believe a shifting is required due to resampling. It does not resample to the middle of the interval!

- [ ] The functional tests must be checked. They currently fail, probably cause there is now wind in the data, which has not been before. But it is important to run these tests and see, whether really only these wanted changes are introduced. If you could show it through screenshots or similar, it is easiest for the community to verify. 

- [ ] Once confirmed there are only wanted changes. Update the test "result-files" with the new wanted result. You can find a guide here: https://github.com/RWTH-EBC/AixWeather/blob/b6adf79b33aa35f4b29e235e8f09010e77608cdd/tests/info#L2

**Review by MartinRaetz — CHANGES_REQUESTED** [review]
Thank you @Jun-Jiang-92. 
Though, we need to verify that the current behavior ist correct.

- [ ] Please review the time shifting required. See my comment in the Issue. I believe a shifting is required due to resampling. It does not resample to the middle of the interval!

- [ ] The functional tests must be checked. They currently fail, probably cause there is now wind in the data, which has not been before. But it is important to run these tests and see, whether really only these wanted changes are introduced. If you could show it through screenshots or similar, it is easiest for the community to verify. 

- [ ] Once confirmed there are only wanted changes. Update the test "result-files" with the new wanted result. You can find a guide here: https://github.com/RWTH-EBC/AixWeather/blob/b6adf79b33aa35f4b29e235e8f09010e77608cdd/tests/info#L2

**Comment by Jun-Jiang-92** [comment]
Screenshots of changed values: only values of wind speed and wind direction changed
As examples here, data of .mos and .csv
grafik
grafik

**Comment by Jun-Jiang-92** [comment]
@MartinRaetz I checked the resample methodology and updated the result files of tests.

You mentioned in #62 that the resample methodology would be "pre2ind". However, I used "foll2ind" for values of wind speed and wind direction by the current version, same as 7 other parameters such as "RelHum", "DryBulbTemp", and so on defined by you.

I studied how this resample methodology works. Before time shifting, the df is already be resampled hourly. By default, pandas will use the averaged value for all the values from 01:00 to 02:00 as the resampled value of 01:00. By using "foll2ind", this time stamp will be shifted to 01:30. This is actually something we want, since it set the time stamp in the middle of each resample period. By using "pre2ind", in contrast, the time stamp will be shifted to 00:30 and it goes 30 minutes ealier than the start of measurement period. So, basically, the method "pre2ind" cannot be used for any parameters. Is that right?

Feel free to write me if there is anything else that should be changed for this merge.

**Review by MartinRaetz — APPROVED** [review]
@Jun-Jiang-92 Thank you for the changes!

You are absolutely right! I was hinting toward prec2ind because I was viewing the wrong dictionary. 
I have changed the base branch to development.

All perfect, the CI only fails due to issues with github pages which are unrelated to this PR. Hence, we can merge!

@Jun-Jiang-92 - Would you like to have these changes in the webapp, as well?
If yes, we need to merge the dev into the main, update the version and set some version update in the changelog. And do the PyPi Release.
After that, we need to contact our software developer to update the repo on the VM.

**Pull request merged**
