### PR TITLE
65 error dwd

### LINKED ISSUE #65: Error for historical DWD import
**Describe the bug**
Loading data with the following script for Tempelhof Berlin historical data, I get values -999 for temperatures not recognized as NAN and IndexErrors.

**To Reproduce**
Steps to reproduce the behavior in current dev.
```
    # initiate the project class which contains or creates all variables and functions
    for year in [
        2019,
        2022,
        2023
    ]:
        DWD_pull_project = ProjectClassDWDHistorical(
            start=dt.datetime(year, 1, 1),
            end=dt.datetime(year + 1, 1, 1),
            station=433,  # Dahlem
            # specify whether nan-values should be filled when exporting
            fillna=True,
            # define results path if desired
            abs_result_folder_path=None,
        )
        # import historical weather from the DWD open access database
        DWD_pull_project.import_data()
```

**Expected behavior**
No errors.

### PR DESCRIPTION
**Pull request by FWuellhorst**
Closes #65 

As discussed @MartinRaetz

### CODE REVIEW

**Review by MartinRaetz — APPROVED** [review]
Integrity should be handled within the code afterwards through deleting duplicates. So there should be no problem with setting it to false.

Defining nan values is part of the desired methodology and any addition here is desired and valueable. 

Though, the function tests seem to fail. From my quick check I cannot clearly tell what is failing. 
Either undesired unexpected behavior, or changed values through correcting the previously wrong interpolation between a  999(now a NaN value) and the next time steps temperature reading. 

Code changes are approved, though. 

Thanks for the changes!

**Comment by FWuellhorst** [comment]
Thanks for the review. I checked locally, it is the new nan values leading to the error. The verify integrity has not impact on the tests. Can you re-generate the reference results? I forgot how to do it.

**Comment by MartinRaetz** [comment]
@FWuellhorst thank you for checking!

You will find a guide how to do it here, it´s easy:
https://github.com/RWTH-EBC/AixWeather/blob/development/tests/info

**Comment by MartinRaetz** [comment]
Pipeline failed only cause of GitHub Pages, this is unrelated to this PR and merging is okay from my side.

**Comment by FWuellhorst** [comment]
Ok! Thanks for updating the results and adding other defaults!

**Pull request merged**
